Repository EstuResidencia/backend, pull requests merged in 2023-11, with the labels that each got.

#4 Develop into Main
  accounts/__init__.py
  accounts/admin/__init__.py
  accounts/admin/admin.py
  accounts/apps.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_user_foto.py
  accounts/migrations/__init__.py
  accounts/models/__init__.py
  accounts/models/manager.py
  accounts/models/user.py
  accounts/serializers/__init__.py
  accounts/serializers/user_login_serializer.py
  accounts/serializers/user_serializer.py
  accounts/tests/__init__.py
  accounts/tests/tests.py
  accounts/urls.py
  accounts/views/__init__.py
  accounts/views/views.py
  arriendos/__init__.py
  arriendos/admin/__init__.py
  arriendos/admin/imagen_admin.py
  arriendos/admin/publicacion_admin.py
  arriendos/admin/resena_admin.py
  arriendos/admin/solicitud_admin.py
  arriendos/apps.py
  arriendos/migrations/0001_initial.py
  arriendos/migrations/__init__.py
  arriendos/models/__init__.py
  arriendos/models/imagen.py
  arriendos/models/publicacion.py
  arriendos/models/resena.py
  arriendos/models/solicitud.py
  arriendos/serializers/__init__.py
  arriendos/tests/__init__.py
  arriendos/tests/tests.py
  arriendos/urls.py
  arriendos/views/__init__.py
  arriendos/views/views.py
  estu_residencia/settings.py
  estu_residencia/urls.py
  poetry.lock
  pyproject.toml
Labels: enhancement

#5 Fix request format
  accounts/admin/admin.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_user_foto.py
  accounts/models/user.py
  accounts/views/views.py
  arriendos/migrations/0001_initial.py
  arriendos/models/publicacion.py
  arriendos/models/solicitud.py
  build.sh
  estu_residencia/settings.py
  poetry.lock
  pyproject.toml
Labels: bug

#6 Develop into main
  accounts/admin/admin.py
  accounts/migrations/0001_initial.py
  accounts/migrations/0002_alter_user_foto.py
  accounts/models/user.py
  accounts/views/views.py
  arriendos/migrations/0001_initial.py
  arriendos/models/publicacion.py
  arriendos/models/solicitud.py
  build.sh
  estu_residencia/settings.py
  poetry.lock
  pyproject.toml
Labels: documentation

#9 Feature/placeholder files
  accounts/urls.py
  arriendos/serializers/imagen_serializer.py
  arriendos/serializers/publicacion_serializer.py
  arriendos/serializers/resena_serializer.py
  arriendos/serializers/solicitud_serializer.py
  arriendos/tests/publicacion_tests.py
  arriendos/tests/resena_tests.py
  arriendos/tests/solicitud_tests.py
  arriendos/tests/tests.py
  arriendos/urls.py
  arriendos/views/notificacion_views.py
  arriendos/views/publicacion_views.py
  arriendos/views/resena_views.py
  arriendos/views/solicitud_views.py
  arriendos/views/views.py
Labels: enhancement

#8 Removed tipo_residencia and habitaciones atributes from publicacion m…
  arriendos/models/publicacion.py
Labels: documentation, enhancement

#10 Tests user endpoints
  accounts/models/manager.py
  accounts/tests/tests.py
  accounts/tests/user_tests.py
Labels: documentation

#11 Plus update/delete user
  accounts/tests/user_tests.py
  accounts/urls.py
  accounts/views/views.py
Labels: enhancement

#14 Test/resena notif
  arriendos/tests/resena_tests.py
Labels: enhancement

#15 Test publicacion
  accounts/tests/user_tests.py
  arriendos/tests/publicacion_tests.py
Labels: documentation

#16 Test/solicitud
  arriendos/models/imagen.py
  arriendos/tests/solicitud_tests.py
Labels: enhancement

#18 Feature publicacion
  arriendos/serializers/publicacion_serializer.py
  arriendos/tests/publicacion_tests.py
  arriendos/views/publicacion_views.py
Labels: documentation, enhancement

#19 Develop
  accounts/tests/user_tests.py
  arriendos/models/imagen.py
  arriendos/serializers/imagen_serializer.py
  arriendos/serializers/publicacion_serializer.py
  arriendos/serializers/resena_serializer.py
  arriendos/serializers/solicitud_serializer.py
  arriendos/tests/__init__.py
  arriendos/tests/publicacion_tests.py
  arriendos/tests/resena_tests.py
  arriendos/tests/solicitud_tests.py
  arriendos/views/notificacion_views.py
  arriendos/views/publicacion_views.py
  arriendos/views/resena_views.py
Labels: enhancement

#20 Implemented solicitud endpoints
  arriendos/serializers/solicitud_serializer.py
  arriendos/tests/solicitud_tests.py
  arriendos/views/publicacion_views.py
  arriendos/views/solicitud_views.py
Labels: documentation, enhancement

#21 Develop
  arriendos/serializers/solicitud_serializer.py
  arriendos/tests/solicitud_tests.py
  arriendos/views/publicacion_views.py
  arriendos/views/solicitud_views.py
Labels: documentation, enhancement

#22 fixed notificacion test
  arriendos/tests/resena_tests.py
Labels: bug, documentation

#23 Add GET method in update_delete_publicacion endpoint
  arriendos/urls.py
  arriendos/views/publicacion_views.py
Labels: enhancement
